"""empty message

Revision ID: 8e3e8e10cae5
Revises: 
Create Date: 2018-04-12 10:37:01.490953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3e8e10cae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('vendedor', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['clienteId'], ['Cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VendaDetalhe',
    sa.Column('vendaId', sa.Integer(), nullable=False),
    sa.Column('produtoId', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produtoId'], ['Produto.id'], ),
    sa.ForeignKeyConstraint(['vendaId'], ['Venda.id'], ),
    sa.PrimaryKeyConstraint('vendaId', 'produtoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VendaDetalhe')
    op.drop_table('Venda')
    op.drop_table('Produto')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
